name: Publish Release
on:
  workflow_dispatch:
env:
  bintray_user: ${{ secrets.bintray_user }}
  bintray_key: ${{ secrets.bintray_key }}

jobs:
  release:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:15-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build bintrayUpload --stacktrace --parrallel
      - uses: ncipollo/release-action@v1.4.0
        with:
            artifacts: |
              ./build/libs/patchwork-patcher-*-ui.jar
              ./build/libs/patchwork-patcher-*-cli.jar
            token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v5
        with:
          add: '.version'
          author_name: Github Actions
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: Update version after release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}